让我们来看一个例子:

```Python
def Main(operation, args):
    nargs = len(args)

    if nargs == 0:
        print("No args")
        return 0

    elif operation == 'generateAlien':
        temp_alienName = args[0]
        temp_owner = args[1]
        if not CheckWitness(temp_owner):
            return 0
        temp_blockHeight = GetHeight()
        temp_xna = FindXna(RandomNumber(temp_blockHeight))
        temp_alien = generateAlien(temp_xna, temp_alienName, temp_blockHeight)
        return temp_alien
```

通过使用 `temp_owner` 调用 `CheckWitness`， 我们可以确定 `temp_owner` 是否是调用智能合约的人，

（*有待更改*）
应当指出的是，在 Python 中，我们总是抛出的`Exception`不是指返回 `false` ，除此之外抛出异常还具有还原所有存储更改的作用。这样可以确保在操作中断言失败时，不会有错误的存储更改。
应当指出的是，在 Python 合约中，我们总是选择抛出`Exception`而不是返回 `false`。 这不仅是因为更切合 Python 的写法，并且能够回滚之前对存储区所做有所改动。


### 指令：

- 添加方法`generateAlien`用于所有者的检查。
  如果检查失败则返回的异常信息。
- 添加一个名为`query`的新方法。请记住检查id是否超出索引。
